import { UpgradeDefinition } from './upgradeTypes';

export const upgradeData: UpgradeDefinition[] = [
  {
    id: 'f_tap_focus',
    category: 'fantasy',
    name: 'Arcane Tap Focus',
    description: 'Increases manual mana gain per shot.',
    baseCost: 20,
    growth: 1.35,
    maxLevel: 40,
    effectLabel: (level) => `+${level} mana/shot`,
  },
  {
    id: 'f_auto_font',
    category: 'fantasy',
    name: 'Mana Font',
    description: 'Boosts passive mana gain each second.',
    baseCost: 45,
    growth: 1.4,
    maxLevel: 30,
    effectLabel: (level) => `+${(level * 0.7).toFixed(1)} mana/s`,
  },
  {
    id: 'f_world_link',
    category: 'fantasy',
    name: 'Astral Relay',
    description: 'Fantasy progress boosts Skybase auto income.',
    baseCost: 90,
    growth: 1.55,
    maxLevel: 20,
    effectLabel: (level) => `+${(level * 0.2).toFixed(1)} sky energy/s`,
    gate: { world: 'skybase', minTier: 2, message: 'Reach Skybase Tier 2 to stabilize this relay.' },
  },
  {
    id: 's_tap_focus',
    category: 'skybase',
    name: 'Capacitor Trigger',
    description: 'Increases manual energy gain per shot.',
    baseCost: 20,
    growth: 1.35,
    maxLevel: 40,
    effectLabel: (level) => `+${level} energy/shot`,
  },
  {
    id: 's_auto_reactor',
    category: 'skybase',
    name: 'Reactor Throughput',
    description: 'Boosts passive energy generation.',
    baseCost: 45,
    growth: 1.4,
    maxLevel: 30,
    effectLabel: (level) => `+${(level * 0.7).toFixed(1)} energy/s`,
  },
  {
    id: 's_world_link',
    category: 'skybase',
    name: 'Quantum Uplink',
    description: 'Skybase progress boosts Fantasy auto income.',
    baseCost: 90,
    growth: 1.55,
    maxLevel: 20,
    effectLabel: (level) => `+${(level * 0.2).toFixed(1)} fantasy mana/s`,
    gate: { world: 'fantasy', minTier: 2, message: 'Reach Fantasy Tier 2 to sync this uplink.' },
  },
  {
    id: 'm_tap_global',
    category: 'meta',
    name: 'Nexus Compression',
    description: 'Global tap multiplier in all worlds.',
    baseCost: 160,
    growth: 1.6,
    maxLevel: 15,
    effectLabel: (level) => `${(1 + level * 0.1).toFixed(2)}x tap gain`,
    prerequisites: [{ upgradeId: 'f_tap_focus', level: 3 }, { upgradeId: 's_tap_focus', level: 3 }],
  },
  {
    id: 'm_gate_authority',
    category: 'meta',
    name: 'Link Authority',
    description: 'Raises the inter-world tier gap gate by +1 per level.',
    baseCost: 220,
    growth: 1.7,
    maxLevel: 6,
    effectLabel: (level) => `Tier gate slack +${level}`,
  },
];
