import { StyleSheet } from 'react-native';

export const hudStyles = StyleSheet.create({
  root: { ...StyleSheet.absoluteFillObject, justifyContent: 'space-between' },
  topWrap: { paddingHorizontal: 12, gap: 8 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 10 },
  leftStack: { gap: 8, flex: 1, maxWidth: '62%' },
  rightStack: { gap: 8, alignItems: 'flex-end', flexShrink: 1 },
  pill: {
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(11,16,28,0.85)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  pillText: { color: 'white', fontWeight: '800', fontSize: 12 },
  upgradesButton: {
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: 'rgba(86,120,255,0.94)',
    borderWidth: 1,
    borderColor: 'rgba(214,225,255,0.85)',
  },
  upgradesText: { color: '#f8fbff', fontWeight: '900', fontSize: 12, letterSpacing: 0.5 },
  bottomRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', paddingHorizontal: 16, paddingBottom: 4 },
  joystickOuter: {
    width: 118,
    height: 118,
    borderRadius: 59,
    backgroundColor: 'rgba(0,0,0,0.55)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(200,214,255,0.24)',
  },
  joystickRing: {
    width: 98,
    height: 98,
    borderRadius: 49,
    backgroundColor: 'rgba(16,23,39,0.9)',
    borderWidth: 1,
    borderColor: 'rgba(170,190,230,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  joystick: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(53,63,88,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(220,228,255,0.28)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  shootBtn: {
    minWidth: 154,
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#3f74ff',
    borderWidth: 1,
    borderColor: '#9cb9ff',
  },
  shootText: { color: 'white', fontWeight: '900', fontSize: 18, textAlign: 'center' },
});
